import { Mock } from "./types.ts";

export const PLATFORM_TEMPLATES: Record<string, Mock[]> = {
  PS4: [
    {
      id: crypto.randomUUID(),
      method: "POST",
      endpoint: "/v3/profiles/sessions",
      status: 200,
      headers: {
        "Ubi-AppId": "ea912bf2-0913-4040-bf85-3519f663441e",
        Authorization: "ubi_v1 t=xxx",
        "Ubi-LocaleCode": "en-US",
        "Content-Type": "application/json",
        "Ubi-RequestedPlatformType": "uplay",
        "Ubi-RoamingProfileId": "none",
        GenomeId: "6661a593-2c78-461c-b0bc-e5f534b1f14f",
      },
      body: {
        platformType: "PS4",
        ticket: "string",
        twoFactorAuthenticationTicket: "string",
        profileId: "string",
        userId: "string",
        nameOnPlatform: "string",
        environment: "UAT",
        expiration: "string",
        spaceId: "string",
        clientIp: "string",
        clientIpCountry: "string",
        serverTime: "string",
        sessionId: "string",
        rememberMeTicket: "string",
        sessionKey: "string",
        codeGenerationPreference: ["string"],
        codeCommunicationPreference: "string",
        maskedPhone: "string",
      },
      active: true,
      endpointUrl: "public-ubiservices.ubi.com",
    },
    {
      id: crypto.randomUUID(),
      method: "GET",
      endpoint: "/v3/profiles/me/external",
      status: 200,
      headers: {
        Origin: "https://uat-connect.cdn.ubisoft.com",
        Referer:
          "https://uat-connect.cdn.ubisoft.com/overlay/default/?microApp=auth&microAppParams=&spaceId=&applicationId=49f1a191-b6ab-4325-94ee-047f33053144&platform=xone-gdk&locale=en-US&sdkVersion=2020.Release.63&env=uat&deviceType=tv&platformVariant=",
        Accept: "*/*",
        "Accept-Language": "en-US",
        Authorization: "psn2.0 t=12690596555501720811;[TOKEN_REDACTED]",
        "Content-Type": "application/json",
        "ubi-appid": "2c2d31af-4ee4-4049-85dc-00dc74aef88f",
        "ubi-sessionid": "ee4bc7d7-661f-404f-b920-1158b0b7157b",
        "Accept-Encoding": "gzip, deflate, br",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; MSAuthHost/1.0)",
        Host: "uat-public-ubiservices.ubi.com",
        Connection: "Keep-Alive",
      },
      body: {
        country: "RO",
        dateOfBirth: "1992-05-23T00:00:00.0000000",
        email: "string@gmail.com",
      },
      active: true,
      endpointUrl: "public-ubiservices.ubi.com",
    },
  ],
  PS5: [
    {
      id: crypto.randomUUID(),
      method: "POST",
      endpoint: "/v3/profiles/sessions",
      status: 200,
      headers: {
        "Ubi-AppId": "ea912bf2-0913-4040-bf85-3519f663441e",
        Authorization: "ubi_v1 t=xxx",
        "Ubi-LocaleCode": "en-US",
        "Content-Type": "application/json",
        "Ubi-RequestedPlatformType": "uplay",
        "Ubi-RoamingProfileId": "none",
        GenomeId: "6661a593-2c78-461c-b0bc-e5f534b1f14f",
      },
      body: {
        platformType: "PS5",
        ticket: "string",
        twoFactorAuthenticationTicket: "string",
        profileId: "string",
        userId: "string",
        nameOnPlatform: "string",
        environment: "UAT",
        expiration: "string",
        spaceId: "string",
        clientIp: "string",
        clientIpCountry: "string",
        serverTime: "string",
        sessionId: "string",
        rememberMeTicket: "string",
        sessionKey: "string",
        codeGenerationPreference: ["string"],
        codeCommunicationPreference: "string",
        maskedPhone: "string",
      },
      active: true,
      endpointUrl: "public-ubiservices.ubi.com",
    },
    {
      id: crypto.randomUUID(),
      method: "GET",
      endpoint: "/v3/profiles/me/external",
      status: 200,
      headers: {
        Origin: "https://uat-connect.cdn.ubisoft.com",
        Referer:
          "https://uat-connect.cdn.ubisoft.com/overlay/default/?microApp=auth&microAppParams=&spaceId=&applicationId=49f1a191-b6ab-4325-94ee-047f33053144&platform=xone-gdk&locale=en-US&sdkVersion=2020.Release.63&env=uat&deviceType=tv&platformVariant=",
        Accept: "*/*",
        "Accept-Language": "en-US",
        Authorization: "psn5.0 t=12690596555501720811;[TOKEN_REDACTED]",
        "Content-Type": "application/json",
        "ubi-appid": "2c2d31af-4ee4-4049-85dc-00dc74aef88f",
        "ubi-sessionid": "ee4bc7d7-661f-404f-b920-1158b0b7157b",
        "Accept-Encoding": "gzip, deflate, br",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; MSAuthHost/1.0)",
        Host: "uat-public-ubiservices.ubi.com",
        Connection: "Keep-Alive",
      },
      body: {
        country: "RO",
        dateOfBirth: "1992-05-23T00:00:00.0000000",
      },
      active: true,
      endpointUrl: "public-ubiservices.ubi.com",
    },
  ],
  XBX: [
    {
      id: crypto.randomUUID(),
      method: "POST",
      endpoint: "/v3/profiles/sessions",
      status: 200,
      headers: {
        "Ubi-AppId": "ea912bf2-0913-4040-bf85-3519f663441e",
        Authorization: "ubi_v1 t=xxx",
        "Ubi-LocaleCode": "en-US",
        "Content-Type": "application/json",
        "Ubi-RequestedPlatformType": "uplay",
        "Ubi-RoamingProfileId": "none",
        GenomeId: "6661a593-2c78-461c-b0bc-e5f534b1f14f",
      },
      body: {
        platformType: "XBX",
        ticket: "string",
        twoFactorAuthenticationTicket: "string",
        profileId: "string",
        userId: "string",
        nameOnPlatform: "string",
        environment: "UAT",
        expiration: "string",
        spaceId: "string",
        clientIp: "string",
        clientIpCountry: "string",
        serverTime: "string",
        sessionId: "string",
        rememberMeTicket: "string",
        sessionKey: "string",
        codeGenerationPreference: ["string"],
        codeCommunicationPreference: "string",
        maskedPhone: "string",
      },
      active: true,
      endpointUrl: "public-ubiservices.ubi.com",
    },
    {
      id: crypto.randomUUID(),
      method: "GET",
      endpoint: "/v3/profiles/me/external",
      status: 200,
      headers: {
        Origin: "https://uat-connect.cdn.ubisoft.com",
        Referer:
          "https://uat-connect.cdn.ubisoft.com/overlay/default/?microApp=auth&microAppParams=&spaceId=&applicationId=49f1a191-b6ab-4325-94ee-047f33053144&platform=xone-gdk&locale=en-US&sdkVersion=2020.Release.63&env=uat&deviceType=tv&platformVariant=",
        Accept: "*/*",
        "Accept-Language": "en-US",
        Authorization: "xbl3.0 t=12690596555501720811;[TOKEN_REDACTED]",
        "Content-Type": "application/json",
        "ubi-appid": "2c2d31af-4ee4-4049-85dc-00dc74aef88f",
        "ubi-sessionid": "ee4bc7d7-661f-404f-b920-1158b0b7157b",
        "Accept-Encoding": "gzip, deflate, br",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; MSAuthHost/1.0)",
        Host: "uat-public-ubiservices.ubi.com",
        Connection: "Keep-Alive",
      },
      body: {
        country: "RO",
        dateOfBirth: "1992-05-23T00:00:00.0000000",
        email: "string@gmail.com",
      },
      active: true,
      endpointUrl: "public-ubiservices.ubi.com",
    },
  ],
  XB1: [
    {
      id: crypto.randomUUID(),
      method: "POST",
      endpoint: "/v3/profiles/sessions",
      status: 200,
      headers: {
        "Ubi-AppId": "ea912bf2-0913-4040-bf85-3519f663441e",
        Authorization: "ubi_v1 t=xxx",
        "Ubi-LocaleCode": "en-US",
        "Content-Type": "application/json",
        "Ubi-RequestedPlatformType": "uplay",
        "Ubi-RoamingProfileId": "none",
        GenomeId: "6661a593-2c78-461c-b0bc-e5f534b1f14f",
      },
      body: {
        platformType: "XB1",
        ticket: "string",
        twoFactorAuthenticationTicket: "string",
        profileId: "string",
        userId: "string",
        nameOnPlatform: "string",
        environment: "UAT",
        expiration: "string",
        spaceId: "string",
        clientIp: "string",
        clientIpCountry: "string",
        serverTime: "string",
        sessionId: "string",
        rememberMeTicket: "string",
        sessionKey: "string",
        codeGenerationPreference: ["string"],
        codeCommunicationPreference: "string",
        maskedPhone: "string",
      },
      active: true,
      endpointUrl: "public-ubiservices.ubi.com",
    },
    {
      id: crypto.randomUUID(),
      method: "GET",
      endpoint: "/v3/profiles/me/external",
      status: 200,
      headers: {
        Origin: "https://uat-connect.cdn.ubisoft.com",
        Referer:
          "https://uat-connect.cdn.ubisoft.com/overlay/default/?microApp=auth&microAppParams=&spaceId=&applicationId=49f1a191-b6ab-4325-94ee-047f33053144&platform=xone-gdk&locale=en-US&sdkVersion=2020.Release.63&env=uat&deviceType=tv&platformVariant=",
        Accept: "*/*",
        "Accept-Language": "en-US",
        Authorization: "xbl3.0 t=12690596555501720811;[TOKEN_REDACTED]",
        "Content-Type": "application/json",
        "ubi-appid": "2c2d31af-4ee4-4049-85dc-00dc74aef88f",
        "ubi-sessionid": "ee4bc7d7-661f-404f-b920-1158b0b7157b",
        "Accept-Encoding": "gzip, deflate, br",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; MSAuthHost/1.0)",
        Host: "uat-public-ubiservices.ubi.com",
        Connection: "Keep-Alive",
      },
      body: {
        country: "RO",
        dateOfBirth: "1992-05-23T00:00:00.0000000",
        email: "string@gmail.com",
      },
      active: true,
      endpointUrl: "public-ubiservices.ubi.com",
    },
  ],
  Switch: [
    {
      id: crypto.randomUUID(),
      method: "POST",
      endpoint: "/v3/profiles/sessions",
      status: 200,
      headers: {
        "Ubi-AppId": "ea912bf2-0913-4040-bf85-3519f663441e",
        Authorization: "ubi_v1 t=xxx",
        "Ubi-LocaleCode": "en-US",
        "Content-Type": "application/json",
        "Ubi-RequestedPlatformType": "uplay",
        "Ubi-RoamingProfileId": "none",
        GenomeId: "6661a593-2c78-461c-b0bc-e5f534b1f14f",
      },
      body: {
        platformType: "OUNCE",
        ticket: "string",
        twoFactorAuthenticationTicket: "string",
        profileId: "string",
        userId: "string",
        nameOnPlatform: "string",
        environment: "UAT",
        expiration: "string",
        spaceId: "string",
        clientIp: "string",
        clientIpCountry: "string",
        serverTime: "string",
        sessionId: "string",
        rememberMeTicket: "string",
        sessionKey: "string",
        codeGenerationPreference: ["string"],
        codeCommunicationPreference: "string",
        maskedPhone: "string",
      },
      active: true,
      endpointUrl: "public-ubiservices.ubi.com",
    },
    {
      id: crypto.randomUUID(),
      method: "GET",
      endpoint: "/v3/profiles/me/external",
      status: 200,
      headers: {
        Origin: "https://uat-connect.cdn.ubisoft.com",
        Referer:
          "https://uat-connect.cdn.ubisoft.com/overlay/default/?microApp=auth&microAppParams=&spaceId=&applicationId=49f1a191-b6ab-4325-94ee-047f33053144&platform=xone-gdk&locale=en-US&sdkVersion=2020.Release.63&env=uat&deviceType=tv&platformVariant=",
        Accept: "*/*",
        "Accept-Language": "en-US",
        Authorization: "switchauth t=12690596555501720811;[TOKEN_REDACTED]",
        "Content-Type": "application/json",
        "ubi-appid": "2c2d31af-4ee4-4049-85dc-00dc74aef88f",
        "ubi-sessionid": "ee4bc7d7-661f-404f-b920-1158b0b7157b",
        "Accept-Encoding": "gzip, deflate, br",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; MSAuthHost/1.0)",
        Host: "uat-public-ubiservices.ubi.com",
        Connection: "Keep-Alive",
      },
      body: {
        country: "RO",
        dateOfBirth: "1992-05-23T00:00:00.0000000",
        email: "string@gmail.com",
      },
      active: true,
      endpointUrl: "public-ubiservices.ubi.com",
    },
  ],
  PC: [
    {
      id: crypto.randomUUID(),
      method: "POST",
      endpoint: "/v3/profiles/sessions",
      status: 200,
      headers: {
        "Ubi-AppId": "ea912bf2-0913-4040-bf85-3519f663441e",
        Authorization: "ubi_v1 t=xxx",
        "Ubi-LocaleCode": "en-US",
        "Content-Type": "application/json",
        "Ubi-RequestedPlatformType": "uplay",
        "Ubi-RoamingProfileId": "none",
        GenomeId: "6661a593-2c78-461c-b0bc-e5f534b1f14f",
      },
      body: {
        platformType: "OUNCE",
        ticket: "string",
        twoFactorAuthenticationTicket: "string",
        profileId: "string",
        userId: "string",
        nameOnPlatform: "string",
        environment: "UAT",
        expiration: "string",
        spaceId: "string",
        clientIp: "string",
        clientIpCountry: "string",
        serverTime: "string",
        sessionId: "string",
        rememberMeTicket: "string",
        sessionKey: "string",
        codeGenerationPreference: ["string"],
        codeCommunicationPreference: "string",
        maskedPhone: "string",
      },
      active: true,
      endpointUrl: "public-ubiservices.ubi.com",
    },
    {
      id: crypto.randomUUID(),
      method: "GET",
      endpoint: "/v3/profiles/me/external",
      status: 200,
      headers: {
        Origin: "https://uat-connect.cdn.ubisoft.com",
        Referer:
          "https://uat-connect.cdn.ubisoft.com/overlay/default/?microApp=auth&microAppParams=&spaceId=&applicationId=49f1a191-b6ab-4325-94ee-047f33053144&platform=xone-gdk&locale=en-US&sdkVersion=2020.Release.63&env=uat&deviceType=tv&platformVariant=",
        Accept: "*/*",
        "Accept-Language": "en-US",
        Authorization: "switchauth t=12690596555501720811;[TOKEN_REDACTED]",
        "Content-Type": "application/json",
        "ubi-appid": "2c2d31af-4ee4-4049-85dc-00dc74aef88f",
        "ubi-sessionid": "ee4bc7d7-661f-404f-b920-1158b0b7157b",
        "Accept-Encoding": "gzip, deflate, br",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; MSAuthHost/1.0)",
        Host: "uat-public-ubiservices.ubi.com",
        Connection: "Keep-Alive",
      },
      body: {
        country: "RO",
        dateOfBirth: "1992-05-23T00:00:00.0000000",
        email: "string@gmail.com",
      },
      active: true,
      endpointUrl: "public-ubiservices.ubi.com",
    },
  ],
};
